# Broadcast port on LAN(Default: 7)
BroadcastPort = 7

# Broadcast cycle(Default: 3)
BroadcastCycle = 3

# The path where the most recents are stored
RecentsFile = ""

[Auth]
# Requir Authentication
Authentication = true

# Authorized User
Username = "admin"

# Enter the plaintext password, WOLS will automatically encrypted
Password = "admin"

[Llog]
# true: Log to file(Default), 
# false: Not log to file, the console log is not affected
EnableLog = true

# The full name of the path to the log file
# The path separator uses "/" or "\\" (Windows), the same below
LogFile = ""

# The level at which the log is recorded
# 1: Debug; 2: Info 3: Warn 4: Error
LogLevel = 2

[Wols]
# Enable WOLS services(Default: true)
EnableWols = true

# WOLS service port(Default: 12307)
WolsPort = 12307

[Webs]
# Enable WEB services(Default: true)
EnableWebs = true

# WEB service port(Default: 7707)
WebsPort = 7077

# Use HTTP Secure SSL/TSL (https://...) 
EnableTls = false

# Certificate Authority file
CertFile = ""

# Private key file
KeyFile = ""